// Mocks generated by Mockito 5.4.5 from annotations
// in openvine/test/widgets/profile_screen_update_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:nostr_sdk/event.dart' as _i6;
import 'package:openvine/models/user_profile.dart' as _i7;
import 'package:openvine/models/video_event.dart' as _i12;
import 'package:openvine/providers/profile_stats_provider.dart' as _i14;
import 'package:openvine/providers/profile_videos_provider.dart' as _i16;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/content_blocklist_service.dart' as _i13;
import 'package:openvine/services/profile_cache_service.dart' as _i8;
import 'package:openvine/services/social_service.dart' as _i10;
import 'package:openvine/services/user_profile_service.dart' as _i5;
import 'package:openvine/services/video_event_service.dart' as _i11;
import 'package:riverpod/src/framework.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRefreshable_1<T> extends _i1.SmartFake
    implements _i3.Refreshable<T> {
  _FakeRefreshable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOverride_2 extends _i1.SmartFake implements _i3.Override {
  _FakeOverride_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoDisposeFutureProviderElement_3<T> extends _i1.SmartFake
    implements _i3.AutoDisposeFutureProviderElement<T> {
  _FakeAutoDisposeFutureProviderElement_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderSubscription_4<State> extends _i1.SmartFake
    implements _i3.ProviderSubscription<State> {
  _FakeProviderSubscription_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_5<T> extends _i1.SmartFake implements _i3.AsyncValue<T> {
  _FakeAsyncValue_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderListenable_6<State> extends _i1.SmartFake
    implements _i3.ProviderListenable<State> {
  _FakeProviderListenable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState => (super.noSuchMethod(
        Invocation.getter(#authState),
        returnValue: _i2.AuthState.unauthenticated,
      ) as _i2.AuthState);

  @override
  _i4.Stream<_i2.AuthState> get authStateStream => (super.noSuchMethod(
        Invocation.getter(#authStateStream),
        returnValue: _i4.Stream<_i2.AuthState>.empty(),
      ) as _i4.Stream<_i2.AuthState>);

  @override
  _i4.Stream<_i2.UserProfile?> get profileStream => (super.noSuchMethod(
        Invocation.getter(#profileStream),
        returnValue: _i4.Stream<_i2.UserProfile?>.empty(),
      ) as _i4.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> get userStats => (super.noSuchMethod(
        Invocation.getter(#userStats),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewIdentity,
          [],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #createNewIdentity,
            [],
            {#biometricPrompt: biometricPrompt},
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromNsec,
          [nsec],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #importFromNsec,
            [nsec],
            {#biometricPrompt: biometricPrompt},
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromHex,
          [privateKeyHex],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #importFromHex,
            [privateKeyHex],
            {#biometricPrompt: biometricPrompt},
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<void> refreshCurrentProfile(
          _i5.UserProfileService? userProfileService) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshCurrentProfile,
          [userProfileService],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signOut({bool? deleteKeys = false}) => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#deleteKeys: deleteKeys},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrivateKeyForSigning,
          [],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportNsec,
          [],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i6.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAndSignEvent,
          [],
          {
            #kind: kind,
            #content: content,
            #tags: tags,
            #biometricPrompt: biometricPrompt,
          },
        ),
        returnValue: _i4.Future<_i6.Event?>.value(),
      ) as _i4.Future<_i6.Event?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i5.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i7.UserProfile> get allProfiles => (super.noSuchMethod(
        Invocation.getter(#allProfiles),
        returnValue: <String, _i7.UserProfile>{},
      ) as Map<String, _i7.UserProfile>);

  @override
  void setPersistentCache(_i8.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(
          #setPersistentCache,
          [cacheService],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedProfile,
        [pubkey],
      )) as _i7.UserProfile?);

  @override
  bool hasProfile(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #hasProfile,
          [pubkey],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #shouldSkipProfileFetch,
          [pubkey],
        ),
        returnValue: false,
      ) as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
        Invocation.method(
          #markProfileAsMissing,
          [pubkey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> updateCachedProfile(_i7.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCachedProfile,
          [profile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProfile,
          [pubkey],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<_i7.UserProfile?>.value(),
      ) as _i4.Future<_i7.UserProfile?>);

  @override
  _i4.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMultipleProfiles,
          [pubkeys],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getDisplayName(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayName,
          [pubkey],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayName,
            [pubkey],
          ),
        ),
      ) as String);

  @override
  String? getAvatarUrl(String? pubkey) => (super.noSuchMethod(Invocation.method(
        #getAvatarUrl,
        [pubkey],
      )) as String?);

  @override
  String? getUserBio(String? pubkey) => (super.noSuchMethod(Invocation.method(
        #getUserBio,
        [pubkey],
      )) as String?);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
        Invocation.method(
          #removeProfile,
          [pubkey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i10.SocialService {
  MockSocialService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> get likedEventIds => (super.noSuchMethod(
        Invocation.getter(#likedEventIds),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  List<String> get followingPubkeys => (super.noSuchMethod(
        Invocation.getter(#followingPubkeys),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool isLiked(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #isLiked,
          [eventId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasReposted(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #hasReposted,
          [eventId],
        ),
        returnValue: false,
      ) as bool);

  @override
  int? getCachedLikeCount(String? eventId) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedLikeCount,
        [eventId],
      )) as int?);

  @override
  bool isFollowing(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #isFollowing,
          [pubkey],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, int>? getCachedFollowerStats(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedFollowerStats,
        [pubkey],
      )) as Map<String, int>?);

  @override
  _i4.Future<void> toggleLike(
    String? eventId,
    String? authorPubkey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [
            eventId,
            authorPubkey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getLikeStatus(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikeStatus,
          [eventId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i6.Event>> fetchLikedEvents(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLikedEvents,
          [pubkey],
        ),
        returnValue: _i4.Future<List<_i6.Event>>.value(<_i6.Event>[]),
      ) as _i4.Future<List<_i6.Event>>);

  @override
  _i4.Future<void> fetchCurrentUserFollowList() => (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentUserFollowList,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> followUser(String? pubkeyToFollow) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [pubkeyToFollow],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unfollowUser(String? pubkeyToUnfollow) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [pubkeyToUnfollow],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowerStats,
          [pubkey],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<int> getUserVideoCount(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #getUserVideoCount,
          [pubkey],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getUserTotalLikes(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #getUserTotalLikes,
          [pubkey],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> postComment({
    required String? content,
    required String? rootEventId,
    required String? rootEventAuthorPubkey,
    String? replyToEventId,
    String? replyToAuthorPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postComment,
          [],
          {
            #content: content,
            #rootEventId: rootEventId,
            #rootEventAuthorPubkey: rootEventAuthorPubkey,
            #replyToEventId: replyToEventId,
            #replyToAuthorPubkey: replyToAuthorPubkey,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i6.Event> fetchCommentsForEvent(String? rootEventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCommentsForEvent,
          [rootEventId],
        ),
        returnValue: _i4.Stream<_i6.Event>.empty(),
      ) as _i4.Stream<_i6.Event>);

  @override
  _i4.Future<int> getCommentCount(String? rootEventId) => (super.noSuchMethod(
        Invocation.method(
          #getCommentCount,
          [rootEventId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> cancelCommentSubscriptions(String? rootEventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelCommentSubscriptions,
          [rootEventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> repostEvent(_i6.Event? eventToRepost) => (super.noSuchMethod(
        Invocation.method(
          #repostEvent,
          [eventToRepost],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> publishRightToBeForgotten() => (super.noSuchMethod(
        Invocation.method(
          #publishRightToBeForgotten,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VideoEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoEventService extends _i1.Mock implements _i11.VideoEventService {
  MockVideoEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.VideoEvent> get videoEvents => (super.noSuchMethod(
        Invocation.getter(#videoEvents),
        returnValue: <_i12.VideoEvent>[],
      ) as List<_i12.VideoEvent>);

  @override
  bool get isSubscribed => (super.noSuchMethod(
        Invocation.getter(#isSubscribed),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasEvents => (super.noSuchMethod(
        Invocation.getter(#hasEvents),
        returnValue: false,
      ) as bool);

  @override
  int get eventCount => (super.noSuchMethod(
        Invocation.getter(#eventCount),
        returnValue: 0,
      ) as int);

  @override
  String get classicVinesPubkey => (super.noSuchMethod(
        Invocation.getter(#classicVinesPubkey),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#classicVinesPubkey),
        ),
      ) as String);

  @override
  void setBlocklistService(_i13.ContentBlocklistService? blocklistService) =>
      super.noSuchMethod(
        Invocation.method(
          #setBlocklistService,
          [blocklistService],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i12.VideoEvent> getVideosByAuthor(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideosByAuthor,
          [pubkey],
        ),
        returnValue: <_i12.VideoEvent>[],
      ) as List<_i12.VideoEvent>);

  @override
  _i4.Future<void> subscribeToVideoFeed({
    List<String>? authors,
    List<String>? hashtags,
    String? group,
    int? since,
    int? until,
    int? limit = 50,
    bool? replace = true,
    bool? includeReposts = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToVideoFeed,
          [],
          {
            #authors: authors,
            #hashtags: hashtags,
            #group: group,
            #since: since,
            #until: until,
            #limit: limit,
            #replace: replace,
            #includeReposts: includeReposts,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> subscribeToUserVideos(
    String? pubkey, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToUserVideos,
          [pubkey],
          {#limit: limit},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> subscribeToHashtagVideos(
    List<String>? hashtags, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToHashtagVideos,
          [hashtags],
          {#limit: limit},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> subscribeToGroupVideos(
    String? group, {
    List<String>? authors,
    int? since,
    int? until,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToGroupVideos,
          [group],
          {
            #authors: authors,
            #since: since,
            #until: until,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i12.VideoEvent> getVideoEventsByGroup(String? group) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByGroup,
          [group],
        ),
        returnValue: <_i12.VideoEvent>[],
      ) as List<_i12.VideoEvent>);

  @override
  _i4.Future<void> refreshVideoFeed() => (super.noSuchMethod(
        Invocation.method(
          #refreshVideoFeed,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadMoreVideos({int? limit = 100}) => (super.noSuchMethod(
        Invocation.method(
          #loadMoreVideos,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadMoreEvents({int? limit = 200}) => (super.noSuchMethod(
        Invocation.method(
          #loadMoreEvents,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadMoreContentUnlimited({int? limit = 300}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreContentUnlimited,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i12.VideoEvent? getVideoEventById(String? eventId) =>
      (super.noSuchMethod(Invocation.method(
        #getVideoEventById,
        [eventId],
      )) as _i12.VideoEvent?);

  @override
  _i12.VideoEvent? getVideoEventByVineId(String? vineId) =>
      (super.noSuchMethod(Invocation.method(
        #getVideoEventByVineId,
        [vineId],
      )) as _i12.VideoEvent?);

  @override
  _i4.Future<_i12.VideoEvent?> queryVideoByVineId(String? vineId) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryVideoByVineId,
          [vineId],
        ),
        returnValue: _i4.Future<_i12.VideoEvent?>.value(),
      ) as _i4.Future<_i12.VideoEvent?>);

  @override
  List<_i12.VideoEvent> getVideoEventsByAuthor(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByAuthor,
          [pubkey],
        ),
        returnValue: <_i12.VideoEvent>[],
      ) as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> getVideoEventsByHashtags(List<String>? hashtags) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByHashtags,
          [hashtags],
        ),
        returnValue: <_i12.VideoEvent>[],
      ) as List<_i12.VideoEvent>);

  @override
  void clearVideoEvents() => super.noSuchMethod(
        Invocation.method(
          #clearVideoEvents,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> unsubscribeFromVideoFeed() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromVideoFeed,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i12.VideoEvent> getVideoEventsByEngagement() => (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByEngagement,
          [],
        ),
        returnValue: <_i12.VideoEvent>[],
      ) as List<_i12.VideoEvent>);

  @override
  List<_i12.VideoEvent> getRecentVideoEvents({int? hours = 24}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentVideoEvents,
          [],
          {#hours: hours},
        ),
        returnValue: <_i12.VideoEvent>[],
      ) as List<_i12.VideoEvent>);

  @override
  Set<String> getUniqueAuthors() => (super.noSuchMethod(
        Invocation.method(
          #getUniqueAuthors,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Set<String> getAllHashtags() => (super.noSuchMethod(
        Invocation.method(
          #getAllHashtags,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Map<String, int> getVideoCountByAuthor() => (super.noSuchMethod(
        Invocation.method(
          #getVideoCountByAuthor,
          [],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  Map<String, dynamic> getConnectionStatus() => (super.noSuchMethod(
        Invocation.method(
          #getConnectionStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> retrySubscription() => (super.noSuchMethod(
        Invocation.method(
          #retrySubscription,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shuffleForDiscovery() => super.noSuchMethod(
        Invocation.method(
          #shuffleForDiscovery,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addVideoEvent(_i12.VideoEvent? videoEvent) => super.noSuchMethod(
        Invocation.method(
          #addVideoEvent,
          [videoEvent],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProfileStatsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileStatsProvider extends _i1.Mock
    implements _i14.ProfileStatsProvider {
  MockProfileStatsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pubkey => (super.noSuchMethod(
        Invocation.getter(#pubkey),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#pubkey),
        ),
      ) as String);

  @override
  _i3.Refreshable<_i4.Future<_i14.ProfileStats>> get future =>
      (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _FakeRefreshable_1<_i4.Future<_i14.ProfileStats>>(
          this,
          Invocation.getter(#future),
        ),
      ) as _i3.Refreshable<_i4.Future<_i14.ProfileStats>>);

  @override
  _i3.Override overrideWith(
          _i4.FutureOr<_i14.ProfileStats> Function(_i14.ProfileStatsRef)?
              create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_2(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i3.Override);

  @override
  _i3.AutoDisposeFutureProviderElement<_i14.ProfileStats> createElement() =>
      (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeAutoDisposeFutureProviderElement_3<_i14.ProfileStats>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i3.AutoDisposeFutureProviderElement<_i14.ProfileStats>);

  @override
  _i3.ProviderSubscription<_i3.AsyncValue<_i14.ProfileStats>> addListener(
    _i15.Node? node,
    void Function(
      _i3.AsyncValue<_i14.ProfileStats>?,
      _i3.AsyncValue<_i14.ProfileStats>,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue:
            _FakeProviderSubscription_4<_i3.AsyncValue<_i14.ProfileStats>>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i3.ProviderSubscription<_i3.AsyncValue<_i14.ProfileStats>>);

  @override
  _i3.AsyncValue<_i14.ProfileStats> read(_i15.Node? node) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValue: _FakeAsyncValue_5<_i14.ProfileStats>(
          this,
          Invocation.method(
            #read,
            [node],
          ),
        ),
      ) as _i3.AsyncValue<_i14.ProfileStats>);

  @override
  _i3.ProviderListenable<Selected> select<Selected>(
          Selected Function(_i3.AsyncValue<_i14.ProfileStats>)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeProviderListenable_6<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i3.ProviderListenable<Selected>);

  @override
  _i3.ProviderListenable<_i4.Future<Output>> selectAsync<Output>(
          Output Function(_i14.ProfileStats)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectAsync,
          [selector],
        ),
        returnValue: _FakeProviderListenable_6<_i4.Future<Output>>(
          this,
          Invocation.method(
            #selectAsync,
            [selector],
          ),
        ),
      ) as _i3.ProviderListenable<_i4.Future<Output>>);
}

/// A class which mocks [ProfileVideosProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileVideosProvider extends _i1.Mock
    implements _i16.ProfileVideosProvider {
  MockProfileVideosProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pubkey => (super.noSuchMethod(
        Invocation.getter(#pubkey),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#pubkey),
        ),
      ) as String);

  @override
  _i3.Refreshable<_i4.Future<List<_i12.VideoEvent>>> get future =>
      (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _FakeRefreshable_1<_i4.Future<List<_i12.VideoEvent>>>(
          this,
          Invocation.getter(#future),
        ),
      ) as _i3.Refreshable<_i4.Future<List<_i12.VideoEvent>>>);

  @override
  _i3.Override overrideWith(
          _i4.FutureOr<List<_i12.VideoEvent>> Function(_i16.ProfileVideosRef)?
              create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_2(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i3.Override);

  @override
  _i3.AutoDisposeFutureProviderElement<List<_i12.VideoEvent>> createElement() =>
      (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue:
            _FakeAutoDisposeFutureProviderElement_3<List<_i12.VideoEvent>>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i3.AutoDisposeFutureProviderElement<List<_i12.VideoEvent>>);

  @override
  _i3.ProviderSubscription<_i3.AsyncValue<List<_i12.VideoEvent>>> addListener(
    _i15.Node? node,
    void Function(
      _i3.AsyncValue<List<_i12.VideoEvent>>?,
      _i3.AsyncValue<List<_i12.VideoEvent>>,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue:
            _FakeProviderSubscription_4<_i3.AsyncValue<List<_i12.VideoEvent>>>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i3.ProviderSubscription<_i3.AsyncValue<List<_i12.VideoEvent>>>);

  @override
  _i3.AsyncValue<List<_i12.VideoEvent>> read(_i15.Node? node) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValue: _FakeAsyncValue_5<List<_i12.VideoEvent>>(
          this,
          Invocation.method(
            #read,
            [node],
          ),
        ),
      ) as _i3.AsyncValue<List<_i12.VideoEvent>>);

  @override
  _i3.ProviderListenable<Selected> select<Selected>(
          Selected Function(_i3.AsyncValue<List<_i12.VideoEvent>>)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeProviderListenable_6<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i3.ProviderListenable<Selected>);

  @override
  _i3.ProviderListenable<_i4.Future<Output>> selectAsync<Output>(
          Output Function(List<_i12.VideoEvent>)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectAsync,
          [selector],
        ),
        returnValue: _FakeProviderListenable_6<_i4.Future<Output>>(
          this,
          Invocation.method(
            #selectAsync,
            [selector],
          ),
        ),
      ) as _i3.ProviderListenable<_i4.Future<Output>>);
}
